import '../models/transaction_model.dart';

final List<TransactionModel> mockTransactions = [
  // ── Transactions for USR001 (Rahul) ──
  TransactionModel(
    id: 'TXN001',
    userId: 'USR001',
    type: 'deposit',
    amount: 5000,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    notes: 'Initial deposit via UPI',
    paymentAccountId: 'ACC002',
    paymentAccountName: 'Account 2 (UPI)',
    depositScreenshotPath: 'dummy:deposit',
  ),
  TransactionModel(
    id: 'TXN002',
    userId: 'USR001',
    type: 'bet_debit',
    amount: 500,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    notes: 'Bet on RCB vs KKR',
  ),
  TransactionModel(
    id: 'TXN003',
    userId: 'USR001',
    type: 'win_credit',
    amount: 3300,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    notes: 'Won bet on IND vs ENG',
  ),
  TransactionModel(
    id: 'TXN004',
    userId: 'USR001',
    type: 'bet_debit',
    amount: 1000,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    notes: 'Bet on DC vs RR Over Runs',
  ),
  TransactionModel(
    id: 'TXN005',
    userId: 'USR001',
    type: 'withdrawal',
    amount: 2000,
    status: 'pending',
    createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    notes: 'Withdrawal to bank account',
    withdrawalPaymentDetails: 'UPI: rahul@hdfc',
    withdrawalScreenshotPath: 'dummy:withdrawal',
  ),

  // ── Transactions for USR002 (Priya) ──
  TransactionModel(
    id: 'TXN006',
    userId: 'USR002',
    type: 'deposit',
    amount: 10000,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(days: 7)),
    notes: 'Initial deposit via bank transfer',
    paymentAccountId: 'ACC001',
    paymentAccountName: 'Account 1 (Bank Transfer)',
    depositScreenshotPath: 'dummy:deposit',
  ),
  TransactionModel(
    id: 'TXN007',
    userId: 'USR002',
    type: 'bet_debit',
    amount: 2000,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    notes: 'Bet on RCB vs KKR',
  ),
  TransactionModel(
    id: 'TXN008',
    userId: 'USR002',
    type: 'win_credit',
    amount: 5700,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    notes: 'Won bet on SRH vs PBKS',
  ),
  TransactionModel(
    id: 'TXN009',
    userId: 'USR002',
    type: 'deposit',
    amount: 3000,
    status: 'pending',
    createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    notes: 'Deposit via UPI',
    paymentAccountId: 'ACC002',
    paymentAccountName: 'Account 2 (UPI)',
    depositScreenshotPath: 'dummy:deposit',
  ),
  TransactionModel(
    id: 'TXN010',
    userId: 'USR002',
    type: 'bet_debit',
    amount: 1500,
    status: 'completed',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    notes: 'Bet on DC vs RR Over Runs',
  ),
];
