import '../models/bet_model.dart';

final List<BetModel> mockBets = [
  // ── Bets for USR001 (Rahul) ──
  BetModel(
    id: 'BET001',
    userId: 'USR001',
    eventId: 'EVT003',
    selectedOption: 'RCB',
    amount: 500,
    multiplier: 1.75,
    status: 'active',
    createdAt: DateTime.now().subtract(const Duration(hours: 1)),
  ),
  BetModel(
    id: 'BET002',
    userId: 'USR001',
    eventId: 'EVT004',
    selectedOption: 'Over 160.5',
    amount: 1000,
    multiplier: 1.95,
    status: 'active',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
  ),
  BetModel(
    id: 'BET003',
    userId: 'USR001',
    eventId: 'EVT005',
    selectedOption: 'India',
    amount: 2000,
    multiplier: 1.65,
    status: 'won',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  BetModel(
    id: 'BET004',
    userId: 'USR001',
    eventId: 'EVT006',
    selectedOption: 'PBKS',
    amount: 500,
    multiplier: 1.90,
    status: 'lost',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
  ),
  BetModel(
    id: 'BET005',
    userId: 'USR001',
    eventId: 'EVT001',
    selectedOption: 'India',
    amount: 1500,
    multiplier: 1.85,
    status: 'active',
    createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
  ),

  // ── Bets for USR002 (Priya) ──
  BetModel(
    id: 'BET006',
    userId: 'USR002',
    eventId: 'EVT003',
    selectedOption: 'KKR',
    amount: 2000,
    multiplier: 2.20,
    status: 'active',
    createdAt: DateTime.now().subtract(const Duration(hours: 1)),
  ),
  BetModel(
    id: 'BET007',
    userId: 'USR002',
    eventId: 'EVT005',
    selectedOption: 'England',
    amount: 1000,
    multiplier: 2.40,
    status: 'lost',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  BetModel(
    id: 'BET008',
    userId: 'USR002',
    eventId: 'EVT006',
    selectedOption: 'SRH',
    amount: 3000,
    multiplier: 1.90,
    status: 'won',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
  ),
  BetModel(
    id: 'BET009',
    userId: 'USR002',
    eventId: 'EVT001',
    selectedOption: 'Australia',
    amount: 500,
    multiplier: 2.10,
    status: 'active',
    createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
  ),
  BetModel(
    id: 'BET010',
    userId: 'USR002',
    eventId: 'EVT004',
    selectedOption: 'Under 160.5',
    amount: 1500,
    multiplier: 1.85,
    status: 'active',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
  ),
];
